<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Contacto";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Contact");
$form->addAction("retweet", "Responder", Com_Helper_Url::getInstance()->urlBase . "/Admin/Contact/Reply");

foreach ($this->languages as $language) {
    $active = false;
    if ($this->Language == $language->LanId) {
        $active = true;
        $form->addTab($language->LanName, Com_Helper_Url::getInstance()->urlBase . "/Admin/Contact/Edit/lan/" . $language->LanId . "/id/" . $this->Id, $active);
    }
}

$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);


$control = new Com_Wizard_Form_Control();
$control->name = "Date";
$control->label = "Date";
$control->default = getLatinDate($this->Date);
$control->length = 50;
$control->readOnly = true;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Name";
$control->label = "Name";
$control->default = $this->Name;
$control->length = 50;
$control->required = true;
$control->readOnly = true;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Email";
$control->label = "Email";
$control->default = $this->Email;
$control->length = 50;
$control->required = true;
$control->readOnly = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Message";
$control->label = "Mensaje";
$control->default = $this->Message;
$control->required = true;
$control->readOnly = true;
$control->rows = 3;
$control->addParameter("style ", "height:120px;");
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'No leido');
$control->addItem('0', 'Leido');
$form->add($control);

$form->render();
