<?PHP

$db = new Entities_Contact();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado Contactos";
$grid->setIdField("ConId");
$grid->setLanField("ConLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "ConDate" => "Fecha", "ConName" => "Nombre", "ConEmail" => "Email", "ConStatus" => "Estado"));
$grid->setFilters(array("ConName" => get('ConName')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Contact/Add');
$toolBar->add("list-alt", "Exportar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Contact/Export');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Contact/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Contact/Delete/id/_ID_' . "':'';");

$grid->customField("ConStatus", array("value" => array('1' => 'No leido', '0' => 'Leido')));

$grid->customField("ConDate", array("dateFormat" => "d/m/Y H:i:s"));

$grid->render();
