<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario BLogs";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Services");

$form->addTab("Idioma por Defecto (" . $this->languages[0]->LanName . ")", "", true);

$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Title";
$control->label = "Titulo";
$control->default = $this->Title;
$control->length = 50;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Resume";
$control->label = "Resumen";
$control->default = $this->Resume;
$control->length = 50;
$control->rows = 3;
$form->add($control);

$control = new Com_Wizard_Form_Control_Editor();
$control->name = "Description";
$control->label = "Descripcion";
$control->default = $this->Description;
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Image";
$control->label = "Image";
$control->default = $this->Image;
$control->required = true;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Icono";
$control->label = "Icono";
$control->default = $this->Icono;
$control->length = 50;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Habilitado');
$control->addItem('0', 'Bloqueado');
$form->add($control);

$form->render();
