<?PHP

$db = new Entities_Services();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado Servicios";
$grid->setIdField("SerId");
$grid->setLanField("SerLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "SerTitle" => "Titulo", "SerStatus" => "Estado"));
$grid->setFilters(array("BloTitle" => get('BloTitle')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Services/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);


$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Services/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Services/Delete/id/_ID_' . "':'';");

$grid->render();
