<?PHP

$db = new Entities_Ticket();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado Tickets";
$grid->setIdField("TikId");
$grid->setLanField("TikLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "TikDate" => "Fecha", "TikName" => "Nombre", "TikEmail" => "Email", "TikStatus" => "Estado"));
$grid->setFilters(array("TikName" => get('tikName')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Ticket/Add');
//$toolBar->add("list-alt", "Exportar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Ticket/Export');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Ticket/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Ticket/Delete/id/_ID_' . "':'';");

$grid->customField("TikStatus", array("value" => array('1' => 'No Atendido', '0' => 'Atendido')));

$grid->customField("TikDate", array("dateFormat" => "d/m/Y H:i:s"));

$grid->render();
