<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario P&aacute;gina";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Pages");

foreach ($this->languages as $language) {
    $active = false;
    if ($this->Language == $language->LanId) {
        $active = true;
    }
    $form->addTab($language->LanName, Com_Helper_Url::getInstance()->urlBase . "/Admin/Pages/Edit/lan/" . $language->LanId . "/id/" . $this->Id, $active);
}

$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Name";
$control->label = "Nombre";
$control->default = $this->Name;
$control->length = 50;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "MetaTags";
$control->label = "MetaTags (SEO)";
$control->default = $this->MetaTags;
$control->required = true;
$control->rows = 3;
$control->addParameter("style ", "height:120px;");
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Description";
$control->label = "Descripcion (SEO)";
$control->default = $this->Description;
$control->required = true;
$control->rows = 3;
$control->addParameter("style ", "height:120px;");
$form->add($control);

$control = new Com_Wizard_Form_Control_CKEditor();
$control->name = "Content";
$control->label = "Contenido";
$control->default = $this->Content;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Aditional";
$control->label = "Contenido Adicional";
$control->default = $this->Aditional;
$control->rows = 3;
$control->addParameter("style ", "height:120px;");
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Image";
$control->label = "Imagen";
$control->default = $this->Image;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Home";
$control->label = "Inicial";
$control->default = $this->Home;
$control->required = true;
$control->addItem('0', 'No');
$control->addItem('1', 'Si');
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Layout";
$control->label = "Plantilla";
$control->default = $this->Layout;
$control->required = true;
$control->addItem('home', 'Home');
$control->addItem('index', 'Inicial');
$control->addItem('contact', 'Contacto');
$control->addItem('about', 'About');
$control->addItem('services', 'Services');
$control->addItem('partners', 'Partners');
$control->addItem('news', 'News');

$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Habilitado');
$control->addItem('0', 'Bloqueado');
$form->add($control);

$form->render();