<?PHP

$db = new Entities_Page();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado P&aacute;ginas";
$grid->setIdField("PagId");
$grid->setLanField("PagLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "PagName" => "Nombre", "PagUrl" => "Url", "PagLayout" => "Tipo", "PagStatus" => "Estado"));
$grid->setFilters(array("PagName" => get('PagName')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Pages/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Pages/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Pages/Delete/id/_ID_' . "':'';");

$grid->customField("PagStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));
$grid->customField("PagLayout", array("value" => array('page' => 'Pagina', 'index' => 'Inicial', 'windows' => "Emergente", 'change' => "Teoria del Cambio", "menu" => "Menu", "pagemenu" => "P&aacute;g. con Cuadros", "pagemenuw" => "P&aacute;g. sin Cuadros")));

$grid->render();
