<div class="col-xs-12 col-md-8">

    <div class="container-fluid content-header-1">
        <div class="row">
            <!--    poner clase bg-note-$color        -->
            <div class="col-sm-3 content-header-1-title bg-note-event">
                <h3>Eventos</h3>
            </div>
            <div class="col-sm-9 content-header-1-options bg-blue-dark-tool">
                <?php foreach ($this->category as $new) { ?>
                    <a class="header-link"
                       href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "events/" . $new->CatId); ?>"><?= $new->CatName; ?></a>
                <?php } ?>
            </div>
        </div>
    </div>
    <section>

        <div
            data-slide-bg="<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $this->events->EveImage; ?>"
            class="swiper-slide" data-swiper-slide-index="1"
            style="background-image: url(<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $this->events->EveImage; ?>); background-size: cover;">
            <div class="pull-bottom">
                <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "events/" . $new->EveCatId); ?>"
                   class="tag bg-note-red"><?= CatEvents_Helper_Category::getInstance()->getId($this->lan, $this->events->EveCatId)->CatName; ?></a>
                <h3><?= $this->events->EveTitle; ?></h3>
                <span><i style="margin-right: 5px" class="fa fa-user"></i><?= $this->events->EveDate; ?></span>
            </div>
        </div>


    </section>
    <div class="container-fluid  content-tool bg-white">
        <div class="row event-body text-left">
            <?= $this->events->EveContent; ?>
            <?php if (!empty($this->events->EveVideo)) { ?>
                <div class="col-ms-12">
                    <p>
                        <iframe width="100%" height="350" src="<?= $this->events->EveVideo; ?>" frameborder="0"
                                allowfullscreen></iframe>
                    </p>
                </div>
            <?php } ?>
            <div class="col-sm-offset-3 col-sm-6">
                <a href="#" class="content-social-link"> <i class="fa fa-twitter"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-facebook"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-instagram"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-youtube"></i></a>
            </div>
        </div>
    </div>
    <div class="container-fluid content-tool bg-white" style="margin-top: 20px">
        <div class="row">
            <div class="fb-comments"
                 data-href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "item/" . $this->events->EveId); ?>"
                 data-numposts="15"></div>
        </div>
    </div>
    <div class="container-fluid content-tool notas-items events-container">
        <div class="row">
            <?php Events_Widget_ByCategory::getInstance()->setLan($this->lan)->setLimit(6)->setCategory($this->events->EveCatId)->render(); ?>

            <div class="col-xs-12" style="padding: 0">
                <?php Advertising_Widget_Ad::getInstance()->setType('F')->setLimit(1)->renderF(); ?>
            </div>
        </div>
    </div>
</div>

