<?PHP

$form = new Com_Wizard_Form();
$form->title = "Editar Perfil";

$control = new Com_Wizard_Form_Control();
$control->name = "Name";
$control->label = "Nombre Completo";
$control->default = $this->Name;
$control->required = true;
$control->length = 50;

$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Image";
$control->label = "Image";
$control->default = $this->Image;
$control->required = true;
$control->isImage = true;

$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Mail";
$control->label = "Mail";
$control->default = $this->Mail;
$control->required = true;
$control->length = 50;

$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Login";
$control->label = "Login";
$control->default = $this->Login;
$control->required = true;
$control->length = 50;

$form->add($control);

$control = new Com_Wizard_Form_Control_Password();
$control->name = "Password";
$control->label = "Password";
$control->required = true;
$control->length = 30;

$form->add($control);

$form->render();
