<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Equipo";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Teams");

foreach ($this->languages as $language) {
    $active = false;
    if ($this->Language == $language->LanId) {
        $active = true;
    }
    $form->addTab($language->LanName, Com_Helper_Url::getInstance()->urlBase . "/Admin/Teams/Edit/lan/" . $language->LanId . "/id/" . $this->Id, $active);
}

$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);


$control = new Com_Wizard_Form_Control();
$control->name = "Nombre";
$control->label = "Nombre";
$control->default = $this->Nombre;
$control->length = 50;
$control->required = true;
$form->add($control);


$control = new Com_Wizard_Form_Control();
$control->name = "Cargo";
$control->label = "Cargo";
$control->default = $this->Cargo;
$control->length = 50;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Resumen";
$control->label = "Resumen";
$control->default = $this->Resumen;
$control->length = 50;
$control->rows = 3;
$form->add($control);

$control = new Com_Wizard_Form_Control_CKEditor();
$control->name = "Contenido";
$control->label = "Contenido";
$control->default = $this->Contenido;
$form->add($control);

$control = new Com_Wizard_Form_Control_CodeEditor();
$control->name = "Info";
$control->label = "Info";
$control->default = $this->Info;
$control->rows = 3;
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Image";
$control->label = "Image";
$control->default = $this->Image;
$control->required = true;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Thumb";
$control->label = "Thumb";
$control->default = $this->Thumb;
$control->required = true;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Habilitado');
$control->addItem('0', 'Bloqueado');
$form->add($control);


$form->render();
