<?PHP

$db = new Entities_Team();
$grid = new Com_Wizard_Grid();
$grid->title = "Equipo";
$grid->setIdField("TeamId");
$grid->setLanField("TeamLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma","TeamCat" => "Cargo", "TeamNombre" => "Nombre", "TeamStatus" => "Estado"));
$grid->setFilters(array("TeamNombre" => get('TeamNombre')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Teams/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);


$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Teams/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Teams/Delete/id/_ID_' . "':'';");

$grid->render();
