<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Notas";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Notes/Index/lan/".$this->Language);


foreach ($this->languages as $language) {
    $active = false;
    if ($this->Language == $language->LanId) {
        $active = true;
    }
    $form->addTab($language->LanName, Com_Helper_Url::getInstance()->urlBase . "/Admin/Notes/Edit/lan/" . $language->LanId . "/id/" . $this->Id, $active);
}

$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);


$control = new Com_Wizard_Form_Control();
$control->name = "Title";
$control->label = "Titulo";
$control->default = $this->Title;
$control->length = 50;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Resume";
$control->label = "Resumen";
$control->default = $this->Resume;
$control->length = 50;
$control->rows = 3;
$form->add($control);

$control = new Com_Wizard_Form_Control_CKEditor();
$control->name = "Description";
$control->label = "Contenido";
$control->default = $this->Description;
$control->required = true;
$control->rows = 3;
$control->addParameter("style ", "height:120px;");
$form->add($control);

$control = new Com_Wizard_Form_Control_Date();
$control->name = "Date";
$control->label = "Fecha";
$control->default = $this->Date;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Author";
$control->label = "Autor";
$control->default = $this->Author;
$control->length = 50;
$control->required = FALSE;
$form->add($control);


$control = new Com_Wizard_Form_Control_File();
$control->name = "Image";
$control->label = "Imagen";
$control->default = $this->Image;
$control->required = true;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Important";
$control->label = "Destacado";
$control->default = $this->Important;
$control->required = true;
$control->addItem('0', 'No');
$control->addItem('1', 'Si');
$form->add($control);


$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Habilitado');
$control->addItem('0', 'Bloqueado');
$form->add($control);

$form->render();
