<section id="buscador" class="container content-section text-center">
    <div class="row  bg-white">
        <div class="col-sm-12">
            <form action="">
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" id="search" placeholder="Buscar">

                        <div class="input-group-addon"><i class="fa fa-search"></i></div>
                    </div>
            </form>
        </div>
    </div>
</section>

<section id="noticias-results" class="container content-section text-center">
    <div class="row  bg-white">

           <ul class="result">
               <li>
                   <a href="http://www.taringa.net/posts/deportes/19494372/ALE-0-2-FRA-Francia-a-la-final-contra-Portugal.html" class="avatar list-l__avatar">
                       <img src="https://t4.kn3.net/taringa/7/1/3/3/2/E/elnegrobigote/92x70_0D3.jpg" class="" alt="ALE 0-2 FRA | Francia a la final contra Portugal" width="92" height="70">
                   </a>
                   <h3>
                       <a href="#" class="list-l__title ">Titulo</a>
                   </h3>
                   <p>lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum </p>
                   <div class="meta list-l__meta">
                       <span class="date pull-right">2016-07-07 <i class="fa fa-calendar"></i></span>
                   </div>
               </li>
               <li>
                   <a href="http://www.taringa.net/posts/deportes/19494372/ALE-0-2-FRA-Francia-a-la-final-contra-Portugal.html" class="avatar list-l__avatar">
                       <img src="https://t4.kn3.net/taringa/7/1/3/3/2/E/elnegrobigote/92x70_0D3.jpg" class="" alt="ALE 0-2 FRA | Francia a la final contra Portugal" width="92" height="70">
                   </a>
                   <h3>
                       <a href="#" class="list-l__title ">Titulo</a>
                   </h3>
                   <p>lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum </p>
                   <div class="meta list-l__meta">
                       <span class="date pull-right">2016-07-07 <i class="fa fa-calendar"></i></span>
                   </div>
               </li>
               <li>
                   <a href="http://www.taringa.net/posts/deportes/19494372/ALE-0-2-FRA-Francia-a-la-final-contra-Portugal.html" class="avatar list-l__avatar">
                       <img src="https://t4.kn3.net/taringa/7/1/3/3/2/E/elnegrobigote/92x70_0D3.jpg" class="" alt="ALE 0-2 FRA | Francia a la final contra Portugal" width="92" height="70">
                   </a>
                   <h3>
                       <a href="#" class="list-l__title ">Titulo</a>
                   </h3>
                   <p>lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum </p>
                   <div class="meta list-l__meta">
                       <span class="date pull-right">2016-07-07 <i class="fa fa-calendar"></i></span>
                   </div>
               </li>
               <li>
                   <a href="http://www.taringa.net/posts/deportes/19494372/ALE-0-2-FRA-Francia-a-la-final-contra-Portugal.html" class="avatar list-l__avatar">
                       <img src="https://t4.kn3.net/taringa/7/1/3/3/2/E/elnegrobigote/92x70_0D3.jpg" class="" alt="ALE 0-2 FRA | Francia a la final contra Portugal" width="92" height="70">
                   </a>
                   <h3>
                       <a href="#" class="list-l__title ">Titulo</a>
                   </h3>
                   <p>lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum </p>
                   <div class="meta list-l__meta">
                       <span class="date pull-right">2016-07-07 <i class="fa fa-calendar"></i></span>
                   </div>
               </li>

           </ul>
            <div><nav>
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav></div>
    </div>

</section>