<?PHP

$db = new Entities_New();
$grid = new Com_Wizard_Grid();

$grid->title = "Listado de Noticias";
$grid->setIdField("NewId");
$grid->setLanField("NewLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "NewDate" => "Fecha", "NewTitle" => "Titulo", "NewUrl" => "Url", "NewStatus" => "Estado"));
$grid->setFilters(array("NewTitle" => get('NewTitle')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/News/Add/');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("plus", "Nueva Categoria", Com_Helper_Url::getInstance()->urlBase . '/Admin/Category');
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/News/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/News/Delete/id/_ID_' . "':'';");

$grid->customField("NewStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));
$grid->customField("NewDate", array("dateFormat" => "d/m/Y"));

$grid->render();
