<!doctype html>
<html class="no-js" lang="">

<head><meta http-equiv="Content-Type" content="text/html; charset=gb18030">
    
     <!-- Google Authorship and Publisher Markup -->
    <link rel="author" href="https://www.wicom.com.bo">
    <link rel="publisher" href="https://www.wicom.com.bo"/>

    <!-- Schema.org markup for Google+ -->
    <meta itemprop="name" content="<?= $this->page->PagName; ?>">
    <meta itemprop="description" content="<?= $this->page->PagDescription; ?>">
    <meta itemprop="image" content="<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?php echo $this->page->PagImage;?>">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@publisher_handle">
    <meta name="twitter:title" content="<?= $this->page->PagName; ?>">
    <meta name="twitter:description" content="<?= $this->page->PagDescription; ?>">
    <meta name="twitter:creator" content="@Wicom">
    <!-- Imagen de sumario de Twitter debe al menos tener 280x150px -->
    <meta name="twitter:image:src" content="<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?php echo $this->page->PagImage;?>">

    <!-- Open Graph data -->
    <meta property="og:title" content="<?= $this->page->PagName; ?>" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="https://www.wicom.com.bo" />
    <meta property="og:image" content="<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?php echo $this->page->PagImage;?>" />
    <meta property="og:description" content="<?= $this->page->PagDescription; ?>" />
    <meta property="og:site_name" content="Wicom" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">
    <title><?= Configurations_Helper_Configuration::getInstance()->getKey('PAGE_TITLE'); ?></title>


    <link rel="apple-touch-icon" sizes="180x180"
        href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png"
        href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png"
        href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/manifest.json">
    <link rel="mask-icon"
        href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/safari-pinned-tab.svg"
        color="#5bbad5">
    <link rel="shortcut icon"
        href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon.ico"
        type="image/x-icon" />

    <?PHP
  Com_Helper_Style::getInstance()
  ->addFile("Public/normalize.css")
  ->addFile("Public/main.css")
  ->addFile("Public/bootstrap.css")
  ->addFile("Public/animate.min.css")
  ->addFile("Public/font-awesome.css")
  ->addFile("Public/owl.carousel.min.css")
  ->addFile("Public/owl.theme.default.min.css")
  ->addFile("Public/meanmenu.min.css")
  ->addFile("Public/colorbox.css")
  ->addFile("Public/preview.css")
  ->addFile("Public/style.css")
  ->addFile("Public/responsive.css")
  ->addFile("Public/nivo-slider.css")
  ->addFile("Public/magnific-popup.css")
  ->addFile("Public/main.css")
  ;


  echo Com_Helper_Style::getInstance();


  ?>

</head>

<body>
    <div class="wrapper-area">
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
        <!-- Header Area Start Here -->
        <header>
            <div class="header-style3-area">
                <div class="main-header-area index2" id="sticker">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                <div class="logo-area">
                                    <a href="<?= Com_Helper_Url::getInstance()->urlBase; ?>/es"><img
                                            class="img-responsive"
                                            src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/logo-3.png"
                                            alt="logo"></a>
                                </div>
                            </div>
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                                <div class="main-menu-area">
                                    <nav>
                                        <ul>
                                            <?php Menu_Widget_Menu::getInstance()->setLan($this->lan)->setParent(1)->render(); ?>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-12">

                            </div>
                        </div>
                    </div>
                    <!-- Mobile Menu Area Start -->
                    <div class="mobile-menu-area">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="mobile-menu">
                                        <nav id="dropdown">
                                            <ul>
                                                <?php Menu_Widget_Menu::getInstance()->setLan($this->lan)->setParent(1)->render(); ?>
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Mobile Menu Area End -->
                </div>
        </header>
        <!-- Header Area End Here -->
        <!-- Slider Area Start Here -->
        <div class="slider-area">
            <div class="overlay"></div>
            <div class="bend-3 niceties preview-3">
                <?php SlideShows_Widget_Slideshow::getInstance()->setLan($this->lan)->renderImages(); ?>

            </div>
        </div>
        <!-- Slider Area End Here -->
        <!-- Home 3 Get A Quote Area Start Here -->
        <div class="get-quote-area">
            <div class="container">
                <div class="inner-get-quote-area">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <h3><?= Texts_Helper_Text::getInstance()->get($this->lan, "quoteSection")->TxtDescription; ?>
                            </h3>
                            <a href="<?=Com_Helper_Url::getInstance()->urlBase.'/'.$this->lan->LanCode. '/page/contacto.html';?>"
                                class="btn-read-more-white"><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtReadMore")->TxtDescription; ?><i
                                    class="fa fa-chevron-right" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Home 3 Get A Quote Area End Here -->
        <!-- Home 3 About Area Start Here -->
        <div class="about-3-area section-space-100-74">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                        <div class="about-3-left">
                            <div class="about-3-left-top">
                                <h2><?= Texts_Helper_Text::getInstance()->get($this->lan, "titleHoWeAre")->TxtDescription; ?>
                                </h2>
                                <?= Texts_Helper_Text::getInstance()->get($this->lan, "contentHoWeAre")->TxtDescription; ?>
                            </div>
                            <a href="<?=Com_Helper_Url::getInstance()->urlBase.'/'.$this->lan->LanCode. '/page/acerca-de.html';?>"
                                class="btn-read-more-fill">Acerca de<i class="fa fa-chevron-right"
                                    aria-hidden="true"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="about-3-right">
                            <a href="#"><img class="img-responsive"
                                    src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/about.jpg"
                                    alt="about"></a>
                        </div>
                    </div>
                </div>
                <div class="row section-space-top">
                    <h3 style="    text-align: center;
	margin: 20px;">Soluciones</h3>

                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="about-3-details" style="margin: 5px;">
                            <div class="media">
                                <a class="pull-left" href="#">
                                    <i class="fa fa-tv" style="font-size: 30px;"></i>
                                </a>
                                <div class="media-body">
                                    <h4>IPTV
                                    </h4>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="about-3-details" style="margin: 5px;">
                            <div class="media">
                                <a class="pull-left" href="#">
                                    <i class="fa fa-tablet" style="font-size: 30px;"></i>
                                </a>
                                <div class="media-body">
                                    <h4>OTT
                                    </h4>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="about-3-details" style="margin: 5px;">
                            <div class="media">
                                <a class="pull-left" href="#">
                                    <i class="fa fa-rss" style="font-size: 30px;"></i>
                                </a>
                                <div class="media-body">
                                    <h4>DHT
                                    </h4>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="about-3-details" style="margin: 5px;">
                            <div class="media">
                                <a class="pull-left" href="#">
                                    <i class="fa fa-database" style="font-size: 30px;"></i>
                                </a>
                                <div class="media-body">
                                    <h4>CDN
                                    </h4>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="about-3-details" style="margin: 5px;">
                            <div class="media">
                                <a class="pull-left" href="#">
                                    <i class="fa fa-globe" style="font-size: 30px;"></i>
                                </a>
                                <div class="media-body">
                                    <h4>CMS
                                    </h4>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="about-3-details" style="margin: 5px;">
                            <div class="media">
                                <a class="pull-left" href="#">
                                    <i class="fa fa-key" style="font-size: 30px;"></i>
                                </a>
                                <div class="media-body">
                                    <h4>Llave en mano
                                    </h4>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Home 3 About Area End Here -->
        <!-- Home 3 Why Choose Us Area Start Here -->
        <div class="why-choose-us-area section-space-88-100">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class="why-choose-us-left">
                            <div class="why-choose-us-title">
                                <h2><?= Texts_Helper_Text::getInstance()->get($this->lan, "whyChooseUsTitle")->TxtDescription; ?>
                                </h2>
                                <p><?= Texts_Helper_Text::getInstance()->get($this->lan, "whyChooseUsContent")->TxtDescription; ?>
                                </p>
                            </div>
                            <div class="why-choose-us-details">
                                <div id="accordion" class="panel-group">
                                    <div class="panel panel-default">
                                        <div class="panel-heading ">
                                            <h4 class="panel-title">
                                                <a href="#collapseOne" data-parent="#accordion" data-toggle="collapse"
                                                    class="accordion-toggle collapsed" aria-expanded="false">
                                                    <span>01.</span>
                                                    <?= Texts_Helper_Text::getInstance()->get($this->lan, "ChooseTitle1")->TxtDescription; ?>
                                                </a>
                                            </h4>
                                        </div>
                                        <div class="panel-collapse collapse" id="collapseOne" aria-expanded="false">
                                            <div class="panel-body">
                                                <?= Texts_Helper_Text::getInstance()->get($this->lan, "ChooseContent1")->TxtDescription; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel panel-default">
                                        <div class="panel-heading active">
                                            <h4 class="panel-title">
                                                <a href="#collapseTwo" data-parent="#accordion" data-toggle="collapse"
                                                    class="accordion-toggle collapsed" aria-expanded="false">
                                                    <span>02.</span>
                                                    <?= Texts_Helper_Text::getInstance()->get($this->lan, "ChooseTitle2")->TxtDescription; ?>
                                                </a>
                                            </h4>
                                        </div>
                                        <div class="panel-collapse collapse in" id="collapseTwo" aria-expanded="false">
                                            <div class="panel-body">
                                                <?= Texts_Helper_Text::getInstance()->get($this->lan, "ChooseContent2")->TxtDescription; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <a href="#collapseThree" data-parent="#accordion" data-toggle="collapse"
                                                    class="accordion-toggle collapsed" aria-expanded="false">
                                                    <span>03.</span>
                                                    <?= Texts_Helper_Text::getInstance()->get($this->lan, "ChooseTitle3")->TxtDescription; ?>
                                                </a>
                                            </h4>
                                        </div>
                                        <div class="panel-collapse collapse" id="collapseThree" aria-expanded="false">
                                            <div class="panel-body">
                                                <?= Texts_Helper_Text::getInstance()->get($this->lan, "ChooseContent3")->TxtDescription; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 hidden-sm"></div>
                </div>
            </div>
        </div>
        <!-- Home 3 Why Choose Us Area End Here -->
        <!-- Home 3 Project Activation Area Start -->
        <!--<div class="project-activation-area section-space-88-75">
            <div class="container">
                <div class="row">
                    <div class="row ab-count">
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <div class="about-counter-list">
                                <h2 class="about-counter">
                                    <?= Texts_Helper_Text::getInstance()->get($this->lan, "counterContent1")->TxtDescription; ?>
                                </h2>
                                <p><?= Texts_Helper_Text::getInstance()->get($this->lan, "counterTitle1")->TxtDescription; ?>
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <div class="about-counter-list">
                                <h2 class="about-counter">
                                    <?= Texts_Helper_Text::getInstance()->get($this->lan, "counterContent2")->TxtDescription; ?>
                                </h2>
                                <p><?= Texts_Helper_Text::getInstance()->get($this->lan, "counterTitle2")->TxtDescription; ?>
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <div class="about-counter-list">
                                <h2 class="about-counter">
                                    <?= Texts_Helper_Text::getInstance()->get($this->lan, "counterContent3")->TxtDescription; ?>
                                </h2>
                                <p><?= Texts_Helper_Text::getInstance()->get($this->lan, "counterTitle3")->TxtDescription; ?>
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <div class="about-counter-list">
                                <h2 class="about-counter">
                                    <?= Texts_Helper_Text::getInstance()->get($this->lan, "counterContent4")->TxtDescription; ?>
                                </h2>
                                <p><?= Texts_Helper_Text::getInstance()->get($this->lan, "counterTitle4")->TxtDescription; ?>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>-->
        <!-- Home 3 Project Activation Area End -->
        <!-- Featured 3 Area Start Here -->
        <!--<div class="featured-3-area section-space-88-100">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="section-title-area">
                            <h2 class="section-title">
                                <?= Texts_Helper_Text::getInstance()->get($this->lan, "featuredWorksTitle")->TxtDescription; ?>
                            </h2>
                            <div class="title-bottom-icon">
                                <span class="title-bottom-icon-left"></span>
                                <i class="fa fa-cubes" aria-hidden="true"></i>
                                <span class="title-bottom-icon-right"></span>
                            </div>
                            <p><?= Texts_Helper_Text::getInstance()->get($this->lan, "featuredWorksContent")->TxtDescription; ?>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row inner-section-space-top hidden">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="isotop-classes-tab ">
                            <a href="#" data-filter="*" class="current">All</a>
                            <a href="#" data-filter=".Buildings">Buildings</a>
                            <a href="#" data-filter=".Construction">Construction</a>
                            <a href="#" data-filter=".Digging">Digging</a>
                            <a href="#" data-filter=".Interior">Interior</a>
                            <a href="#" data-filter=".Tiling">Tiling</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid inner-section-space-top">
                <div class="row featuredContainer">

                    <?PHP Works_Widget_Works::getInstance()->setLan($this->lan)->render(); ?>

                </div>
            </div>
        </div>-->
        <!-- Featured 3 Area End Here -->
        <!-- Our Team Area Start Here -->
        <!--<div class="team-area section-space-88-64">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="section-title-area">
                            <h2 class="section-title">
                                <?= Texts_Helper_Text::getInstance()->get($this->lan, "teamTitle")->TxtDescription; ?>
                            </h2>
                            <div class="title-bottom-icon">
                                <span class="title-bottom-icon-left"></span>
                                <i class="fa fa-cubes" aria-hidden="true"></i>
                                <span class="title-bottom-icon-right"></span>
                            </div>
                            <p><?= Texts_Helper_Text::getInstance()->get($this->lan, "teamContent")->TxtDescription; ?>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row inner-section-space-top">

                    <?PHP Teams_Widget_Team::getInstance()->setLan($this->lan)->render(); ?>
                </div>
            </div>
        </div>-->
        <!-- Our Team Area End Here -->
        <!-- Clients 3 Area Start Here -->
        <div class="clients-3-area section-space-88-94 hidden">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="section-title-area">
                            <h2 class="section-title">What Client's Say</h2>
                            <div class="title-bottom-icon">
                                <span class="title-bottom-icon-left"></span>
                                <i class="fa fa-cubes" aria-hidden="true"></i>
                                <span class="title-bottom-icon-right"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="kon-carousel" data-loop="true" data-items="3" data-margin="30" data-autoplay="true"
                    data-autoplay-timeout="2000" data-smart-speed="2000" data-dots="false" data-nav="true"
                    data-nav-speed="false" data-r-x-small="1" data-r-x-small-nav="false" data-r-x-small-dots="false"
                    data-r-x-medium="1" data-r-x-medium-nav="false" data-r-x-medium-dots="false" data-r-small="2"
                    data-r-small-nav="false" data-r-small-dots="false" data-r-medium="3" data-r-medium-nav="false"
                    data-r-medium-dots="false" data-r-large="3" data-r-large-nav="false" data-r-large-dots="false">
                    <div class="clients-3-box">
                        <div class="clients-3-box-top">
                            <span><i class="fa fa-quote-left" aria-hidden="true"></i></span>
                            <p>Simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                                industry's standard dummy text ever. </p>
                        </div>
                        <img src="img/comment.png" alt="comment">
                        <p><a href="#" title="">Mr. Rashid Rafel</a></p>
                        <p>CEO, Koncrete Construction</p>
                    </div>

                    <div class="clients-3-box">
                        <div class="clients-3-box-top">
                            <span><i class="fa fa-quote-left" aria-hidden="true"></i></span>
                            <p>Simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                                industry's standard dummy text ever. </p>
                        </div>
                        <img src="img/comment.png" alt="comment">
                        <p><a href="#" title="">Mr. Rashid Rafel</a></p>
                        <p>CEO, Koncrete Construction</p>
                    </div>

                    <div class="clients-3-box">
                        <div class="clients-3-box-top">
                            <span><i class="fa fa-quote-left" aria-hidden="true"></i></span>
                            <p>Simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                                industry's standard dummy text ever. </p>
                        </div>
                        <img src="img/comment.png" alt="comment">
                        <p><a href="#" title="">Mr. Rashid Rafel</a></p>
                        <p>CEO, Koncrete Construction</p>
                    </div>
                    <div class="clients-3-box">
                        <div class="clients-3-box-top">
                            <span><i class="fa fa-quote-left" aria-hidden="true"></i></span>
                            <p>Simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                                industry's standard dummy text ever. </p>
                        </div>
                        <img src="img/comment.png" alt="comment">
                        <p><a href="#" title="">Mr. Rashid Rafel</a></p>
                        <p>CEO, Koncrete Construction</p>
                    </div>

                    <div class="clients-3-box">
                        <div class="clients-3-box-top">
                            <span><i class="fa fa-quote-left" aria-hidden="true"></i></span>
                            <p>Simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                                industry's standard dummy text ever. </p>
                        </div>
                        <img src="img/comment.png" alt="comment">
                        <p><a href="#" title="">Mr. Rashid Rafel</a></p>
                        <p>CEO, Koncrete Construction</p>
                    </div>

                    <div class="clients-3-box">
                        <div class="clients-3-box-top">
                            <span><i class="fa fa-quote-left" aria-hidden="true"></i></span>
                            <p>Simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                                industry's standard dummy text ever. </p>
                        </div>
                        <img src="img/comment.png" alt="comment">
                        <p><a href="#" title="">Mr. Rashid Rafel</a></p>
                        <p>CEO, Koncrete Construction</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Clients 3 Area End Here -->
        <!-- News Area Start Here -->
        <div class="news-3-area section-space-88-64 hidden">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="section-title-area">
                            <h2 class="section-title">
                                <?= Texts_Helper_Text::getInstance()->get($this->lan, "newsTitle")->TxtDescription; ?>
                            </h2>
                            <div class="title-bottom-icon">
                                <span class="title-bottom-icon-left"></span>
                                <i class="fa fa-cubes" aria-hidden="true"></i>
                                <span class="title-bottom-icon-right"></span>
                            </div>
                            <p><?= Texts_Helper_Text::getInstance()->get($this->lan, "newsContent")->TxtDescription; ?>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row inner-section-space-top">
                    <div class="col-lg-6 col-md-5 col-sm-12 col-xs-12 news-3-area-left">
                        <?php Notes_Widget_News::getInstance()->setLan($this->lan)->renderImportant(); ?>
                    </div>
                    <div class="col-lg-6 col-md-7 col-sm-12 col-xs-12 news-3-area-right">
                        <div class="row inner-news-3-box-right">
                            <?php Notes_Widget_News::getInstance()->setLan($this->lan)->render(); ?>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- News Area End Here -->
        <!-- Brand Area Start Here -->
        <div class="brand-area">
            <div class="container">
                <div class="brand kon-carousel" data-loop="true" data-items="4" data-margin="10" data-autoplay="true"
                    data-autoplay-timeout="10000" data-smart-speed="2000" data-dots="false" data-nav="true"
                    data-nav-speed="false" data-r-x-small="2" data-r-x-small-nav="true" data-r-x-small-dots="false"
                    data-r-x-medium="3" data-r-x-medium-nav="true" data-r-x-medium-dots="false" data-r-small="4"
                    data-r-small-nav="true" data-r-small-dots="false" data-r-medium="5" data-r-medium-nav="true"
                    data-r-medium-dots="false" data-r-large="4" data-r-large-nav="true" data-r-large-dots="false">
                    <?php Gallery_Widget_Clientes::getInstance()->setLan($this->lan)->render(); ?>

                </div>
            </div>
        </div>
        <!-- Brand Area End Here -->
        <!-- Footer Area Start Here -->
        <?PHP Pages_Widget_Footer::getInstance()->render(); ?>
        <!-- Footer Area End Here -->
    </div>
    <!-- Preloader Start Here -->
    <div id="preloader"></div>


    <?php
    Com_Helper_Script::getInstance()
    ->addFile("Public/modernizr-2.8.3.min.js")
    ->addFile("Public/jquery-1.12.0.min.js")
    ->addFile("Public/bootstrap.min.js")
    ->addFile("Public/owl.carousel.min.js")
    ->addFile("Public/jquery.nivo.slider.js")
    ->addFile("Public/home.js")
    ->addFile("Public/jquery.meanmenu.min.js")
    ->addFile("Public/wow.min.js")
    ->addFile("Public/plugins.js")
    ->addFile("Public/jquery.scrollUp.min.js")
    ->addFile("Public/isotope.pkgd.js")
    ->addFile("Public/jquery.counterup.min.js")
    ->addFile("Public/waypoints.min.js")
    ->addFile("Public/jquery.colorbox-min.js")
    ->addFile("Public/main.js");

    echo Com_Helper_Script::getInstance();
    ?>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAmiJjq5DIg_K9fv6RE72OY__p9jz0YTMI"></script>

    <script type="text/javascript">
    $(function() {
        $('[data-toggle="tooltip"]').tooltip()
    })

    function sendContact() {
        var name = $('#contactForm #name').val();
        var message = $('#contactForm #message').val();
        var email = $('#contactForm #email').val();
        var phone = $('#contactForm #phone').val();

        if (name === "" || email === "" || message === "") {
            //swal("", "Los campos marcados con (*) son obligatorios", "warning");
            console.log("Por favor revise los datos del formulario !!!");
        } else {

            $.ajax({
                type: "POST",
                url: "http://www.barbarapelicula.com.bo/Service/Contact/Save",
                data: {
                    Name: name,
                    Email: email,
                    Phone: phone,
                    Message: message
                }
            }).done(function(data) {
                console.log("Exito");
                // swal("", "Su mensaje fue enviado con exito", "success");
                $('#contactForm #name').val("");
                $('#contactForm #message').val("");
                $('#contactForm #email').val("");
                $('#contactForm #phone').val("");
            }).error(function() {

            });


        }
    }
    </script>
</body>





</html>