<?PHP

$form = new Com_Wizard_Form();
$form->title = "Configuracion de Idioma";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Language");

$control = new Com_Wizard_Form_Control();
$control->name = "Code";
$control->label = "Codigo";
$control->default = $this->Code;
$control->readOnly = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Name";
$control->label = "Name";
$control->default = $this->Name;
$control->readOnly = true;
$control->length = 50;
$form->add($control);



$control = new Com_Wizard_Form_Control_CodeEditor();
$control->name = "File";
$control->label = "Archivo";
$control->default = $this->File;
$form->add($control);

$form->render();
?>