<!DOCTYPE html>
<html lang="es">
    <head>
        <title><?PHP echo CMS_TITLE; ?></title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="robots" content="none">
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">  
        <!-- Fav and Touch Icons -->
        <meta name="msapplication-TileColor" content="#d9534f">
        <meta name="msapplication-TileImage"
              content="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/ms-icon-144x144.png">
        <meta name="msapplication-config"
              content="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public//favicons/browserconfig.xml">
        <meta name="theme-color" content="#ffffff">
        <link rel="apple-touch-icon" sizes="57x57"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-180x180.png">
        <link rel="icon" type="image/png"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-32x32.png"
              sizes="32x32">
        <link rel="icon" type="image/png"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/android-192x192.png"
              sizes="192x192">
        <link rel="icon" type="image/png"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-96x96.png"
              sizes="96x96">
        <link rel="icon" type="image/png"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-16x16.png"
              sizes="16x16">
        <link rel="manifest" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/manifest.json">
        <link rel="shortcut icon"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon.ico"
              type="image/x-icon"/>
              <?PHP
              Com_Helper_Style::getInstance()->addFile("Admin/bootstrap.css")
                      ->addFile("Admin/datepicker.css")
                      ->addFile("Admin/bootstrap.min.css")
                      ->addFile("Admin/jquery.ui.css")
                      ->addFile("Admin/admin.css")
                      ->addFile("Admin/editor.css")
                      ->addFile("Admin/font-awesome.css")
                      ->addFile("Admin/codemirror.css")
                      ->addFile("Admin/jBox.css");

              Com_Helper_Script::getInstance()->addFile("Admin/jquery.min.js")
                      ->addFile("Admin/jquery.ui.js")
                      ->addFile("Admin/jquery.taginput.js")
                      ->addFile("Admin/jquery.jbox.min.js")
                      ->addFile("Admin/jqbrowser.js")
                      ->addFile("Admin/bootstrap.js")
                      ->addFile("Admin/editor.js")
                      ->addFile("Admin/ckeditor/ckeditor.js")
                      ->addFile("Admin/datepicker.js")
                      ->addFile("Admin/codemirror.js")
                      ->addFile("Admin/codemirror.javascript.js")
                      ->addFile("Admin/admin.js");

              echo Com_Helper_Style::getInstance();
              ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><?PHP echo APP_TITLE; ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?PHP
                        echo Com_Helper_Menu::getInstance();
                        ?>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?PHP echo get('userFullName'); ?><span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?PHP echo Com_Helper_Url::getInstance()->urlBase; ?>/Admin/Admin/Account">Mi Cuenta</a></li>
                                <li class="divider"></li>
                                <li><a href="<?PHP echo Com_Helper_Url::getInstance()->urlBase; ?>/Admin/Admin/Close">Salir</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <div class="container">
            <?PHP
            Com_Helper_BreadCrumbs::getInstance()->render();
            Com_Helper_Title::getInstance()->render();
            Com_Wizard_Messages::getInstance()->render();

            $this->getContent();
            ?>
        </div>
        <!--FOOTER QWERTY-->
        <?PHP Pages_Widget_Footer::getInstance()->render(); ?>
        <?PHP
        echo Com_Helper_Script::getInstance();
        ?>
        <script type="text/javascript">
            urlBase = '<?PHP echo Com_Helper_Url::getInstance()->urlBase; ?>';
        </script>

    </body>
</html>