<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Textos de pagina";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Texts");

$form->addTab("Idioma por Defecto (" . $this->languages[0]->LanName . ")", "", true);

$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Alias";
$control->label = "Alias";
$control->default = $this->Alias;
$control->length = 50;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Description";
$control->label = "Descripcion";
$control->default = $this->Description;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Habilitado');
$control->addItem('0', 'Bloqueado');

$form->add($control);

$form->render();
