<?PHP

$db = new Entities_Category();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado Categorias";
$grid->setIdField("CatId");
$grid->setLanField("CatLanId");
$grid->setQuery($db->getWithParents());
$grid->setAlias(array("LanName" => "Idioma", "padre" => "Raiz", "CatAlias" => "Alias", "CatStatus" => "Estado"));
$grid->setFilters(array("Menu.MenAlias" => get('Menu_MenAlias')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("glyphicon glyphicon-plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Categories/Add');
$toolBar->add("sort", "Ordenar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Categories/Order');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');

$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Categories/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Categories/Delete/id/_ID_' . "':'';");

$grid->customField("CatStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));

$grid->render();
