<?PHP

/**
 * avaManager
 * avaManager
 *
 * Description of order
 *
 * @author aortuno
 * @since   Nov 21, 2011 - 6:16:06 PM
 * @filesource order.phtml
 * @package Modules
 * @subpackage View
 * @name order
 */
function hasChilds($parentId, $lstModules)
{
    foreach ($lstModules as $objModule) {
        if ($objModule->CatParentId == $parentId) {
            return true;
        }
    }
    return false;
}

function renderItems($parentId, $lstModules)
{
    if (hasChilds($parentId, $lstModules)) {
        ?>
        <ul class="sortable">
            <?PHP
            foreach ($lstModules as $objModule) {
                if ($objModule->CatParentId == $parentId) {
                    ?>
                    <li>
                        <span class="glyphicon glyphicon-resize-vertical handle" title="Arrastre para mover"></span>

                        <div><?PHP echo $objModule->CatAlias; ?><input type="hidden" name="Order[]"
                                                                       value="<?PHP echo $objModule->CatId; ?>"></div>
                        <?PHP
                        renderItems($objModule->CatId, $lstModules);
                        ?>
                    </li>
                <?PHP
                }
            }
            ?>
        </ul>
    <?PHP
    }
}

$objToolBar = new Com_Wizard_ToolBar();

$objToolBar->add("refresh", "Actualizar", Com_Helper_Url::getInstance()->urlBase . "/Admin/Categories/Order");
$objToolBar->add("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$objToolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Categories");
?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">Ordenar Men&uacute;</div>
        <div class="panel-control">
            <?PHP
            $objToolBar->render();
            ?>
        </div>
    </div>
    <div class="panel-body">
        <div class="formulario">
            <ul class="nav nav-tabs">
                <?PHP
                foreach ($this->languages as $language) {
                    $active = false;
                    if ($this->Language == $language->LanId) {
                        $active = true;
                    }
                    ?>
                    <li class="<?PHP echo($active ? "active" : ""); ?>" role="presentation"><a
                            href="<?PHP echo Com_Helper_Url::getInstance()->urlBase . "/Admin/Categories/Order/lan/" . $language->LanId; ?>"><?PHP echo $language->LanName; ?></a>
                    </li>
                <?PHP
                }
                ?>
            </ul>
            <br/>

            <form method="POST">
                <div class="title"><i>Arrastre para cambiar el orden de los modulos en el menu</i><br/></div>
                <?PHP
                renderItems(0, $this->lstModules);
                ?>
                <div class="buttons" style="display:none;">
                    <div class="button">
                        <input type="submit" value="Guardar" id="saveForm">
                        <input type="reset" value="Limpiar" id="cleanForm">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<style type="text/css">

    .formulario .title {
        font-size: 18px;
        padding: 10px 1%;
    }

    .formulario {
        float: left;
        display: block;
        position: relative;
        width: 100%;
    }

    form {
        width: 100%;
    }

    form ul.sortable {
        border: 1px solid #CCC;
        padding: 2%;
        margin: 0px;
        float: left;
        display: block;
        position: relative;
        clear: both;
        width: 100%;
        background-color: #FFF;
    }

    form ul.sortable li {
        background-color: #DFE5DD;
        margin: 10px 0px;
        padding: 7px 1%;
        float: left;
        display: block;
        position: relative;
        clear: both;
        width: 100%;
    }

    form ul.sortable li span {
        cursor: move;
        float: left;
        display: block;
        position: relative;
        margin: 8px;
        font-size: 26px;
        width: 26px;
        height: 26px;
    }

    form ul.sortable li div {
        float: left;
        display: block;
        position: relative;
        margin: 10px;
        font-size: 16px;
    }
</style>